name: DeFish
version: '1.0.0'
main: de.sonnes.defish.DeFish
api-version: '1.13'
authors: [desonnes]
description: Plugin for random loot from fishing
website: bruhstudio.ru
commands:
  defish:
permissions:
  defish.command.addloot: